name: test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run install.sh
      run: ${GITHUB_WORKSPACE}/install.sh

    - name: Run macos.sh
      run: ${GITHUB_WORKSPACE}/macos.sh

    # TODO: add dotfiles
