name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install shellcheck
      run: brew install shellcheck

    - name: Check install.sh
      run: shellcheck ${GITHUB_WORKSPACE}/install.sh

    - name: Check macos.sh
      run: shellcheck ${GITHUB_WORKSPACE}/macos.sh

    # TODO: add dotfiles
